USE TerminalPuntoDeVentaFarmacia
GO
--INSERT DE RAZON SOCIAL
CREATE PROCEDURE SP_INSERT_RAZONSOCIAL
	@NOMBRE CHAR(150),
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@REFERENCIA CHAR(200),
	@COLONIA CHAR(40),
	@CP INT,
	@RFC CHAR(13),
	@ESTADO CHAR(31),
	@MUNICIPIO CHAR(25),
	@REGIMENFISCAL CHAR(10),
	@TELEFONOUNO INT,
	@TELEFONODOS INT,
	@REDSOCIALUNO CHAR(50),
	@REDSOCIALDOS CHAR(50)
AS
BEGIN
	INSERT razon_social VALUES(@NOMBRE, @CALLE, @NUMEXT, @NUMINT, @REFERENCIA, @COLONIA, @CP, @RFC,
	@ESTADO, @MUNICIPIO, @REGIMENFISCAL, @TELEFONOUNO, @TELEFONODOS, @REDSOCIALUNO, @REDSOCIALDOS)
END
GO

EXECUTE SP_INSERT_RAZONSOCIAL @NOMBRE='Prueba 5',@CALLE='Prueba',@NUMEXT='0',@NUMINT='',@REFERENCIA='Ninguna',
@COLONIA='Prueba',@CP='0',@RFC='0a',@ESTADO='Prueba',@MUNICIPIO='Prueba',@REGIMENFISCAL='Moral',@TELEFONOUNO='',
@TELEFONODOS='',@REDSOCIALUNO='', @REDSOCIALDOS=''
GO

DBCC CHECKIDENT ('razon_social', RESEED, 1);

--UPDATE DE RAZON SOCIAL
CREATE PROCEDURE SP_UPDATE_RAZONSOCIAL
	@ID INT,
	@NOMBRE CHAR(150),
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@REFERENCIA CHAR(200),
	@COLONIA CHAR(40),
	@CP INT,
	@RFC CHAR(13),
	@ESTADO CHAR(31),
	@MUNICIPIO CHAR(25),
	@REGIMENFISCAL CHAR(10),
	@TELEFONOUNO INT,
	@TELEFONODOS INT,
	@REDSOCIALUNO CHAR(50),
	@REDSOCIALDOS CHAR(50)
AS
BEGIN
	UPDATE razon_social SET nombreRS=@NOMBRE, calleRS=@CALLE, numExtRS=@NUMEXT, numIntRS=@NUMINT, referenciaRS=@REFERENCIA, coloniaRS=@COLONIA,
	codigoPostalRS=@CP, rfcRS=@RFC, estadoRS=@ESTADO, municipioRS=@MUNICIPIO, regimenFiscalRS=@REGIMENFISCAL, telefonoUnoRS=@TELEFONOUNO,
	telefonoDosRS=@TELEFONODOS, redSocialUnoRS=@REDSOCIALUNO, redSocialDosRS=@REDSOCIALDOS
	WHERE idRS = @ID
END
GO

--SELECT DE RAZON SOCIAL
CREATE PROCEDURE SP_SELECT_RAZONSOCIAL
	@NOMBRE CHAR(150)
AS
BEGIN
	SELECT idRS, nombreRS FROM razon_social WHERE nombreRS=@NOMBRE
END
GO

EXECUTE SP_SELECT_RAZONSOCIAL @NOMBRE = 'Prueba'
GO

--SELECT DE RAZON SOCIAL DOS
CREATE PROCEDURE SP_SELECT_RAZONSOCIAL_DOS
AS
BEGIN
	SELECT idRS, nombreRS FROM razon_social
END
GO

--SELECT DE RAZON SOCIAL TRES
CREATE PROCEDURE SP_SELECT_RAZONSOCIAL_TRES
AS
BEGIN
	SELECT TOP(1) idRS FROM razon_social
	ORDER BY idRS DESC
END
GO

EXECUTE SP_SELECT_RAZONSOCIAL_TRES
GO

--DELETE DE RAZON SOCIAL
CREATE PROCEDURE SP_DELETE_RAZONSOCIAL
	@ID INT
AS
BEGIN
	DELETE FROM razon_social WHERE idRS=@ID
END
GO

EXECUTE SP_DELETE_RAZONSOCIAL @ID='2'
GO

--INSERT DE SUCURSAL
CREATE PROCEDURE SP_INSERT_SUCURSAL
	@IDRS INT,
	@NOMBRE CHAR(50),
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(25),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31)
AS
BEGIN
	INSERT sucursal VALUES(@IDRS, @NOMBRE, @CALLE, @NUMEXT,
	@NUMINT, @COLONIA, @MUNICIPIO, @CP, @ESTADO)
END
GO

EXECUTE SP_INSERT_SUCURSAL @IDRS='1',@NOMBRE='Prueba',@CALLE='Prueba',@NUMEXT='0',
@NUMINT='',@COLONIA='Prueba',@MUNICIPIO='Prueba',@CP='0',@ESTADO='Prueba'
GO

DBCC CHECKIDENT ('sucursal', RESEED, 1);

--UPDATE DE SUCURSAL
CREATE PROCEDURE SP_UPDATE_SUCURSAL
	@ID INT,
	@IDRS INT,
	@NOMBRE CHAR(50),
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(25),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31)
AS
BEGIN
	UPDATE sucursal SET idRS=@IDRS, nombreSucursal=@NOMBRE, calleSucursal=@CALLE, numExtSucursal=@NUMEXT, numIntSucursal=@NUMINT,
	coloniaSucursal=@COLONIA, municipioSucursal=@MUNICIPIO, codigoPostalSucursal=@CP, estadoSucursal=@ESTADO
	WHERE idSucursal = @ID
END
GO

--SELECT DE SUCURSAL
CREATE PROCEDURE SP_SELECT_SUCURSAL
	@ID INT
AS
BEGIN
	SELECT * FROM sucursal WHERE idSucursal=@ID
END
GO

EXECUTE SP_SELECT_SUCURSAL @ID = '1'
GO

--SELECT DE SUCURSAL DOS
CREATE PROCEDURE SP_SELECT_SUCURSAL_DOS
AS
BEGIN
	SELECT * FROM sucursal
END
GO

EXECUTE SP_SELECT_SUCURSAL_DOS
GO

--DELETE DE SUCURSAL
CREATE PROCEDURE SP_DELETE_SUCURSAL
	@ID INT
AS
BEGIN
	DELETE FROM sucursal WHERE idSucursal=@ID
END
GO

EXECUTE SP_DELETE_SUCURSAL @ID = '2'
GO

--INSERT DE LABORATORIO
CREATE PROCEDURE SP_INSERT_LABORATORIO
	@NOMBRE CHAR(50)
AS
BEGIN
	INSERT laboratorio VALUES(@NOMBRE)
END
GO

--UPDATE DE LABORATORIO
CREATE PROCEDURE SP_UPDATE_LABORATORIO
	@ID INT,
	@NOMBRE CHAR(50)
AS
BEGIN
	UPDATE laboratorio SET nombreLaboratorio=@NOMBRE
	WHERE idLaboratorio = @ID
END
GO

--SELECT DE LABORATORIO
CREATE PROCEDURE SP_SELECT_LABORATORIO
	@ID INT
AS
BEGIN
	SELECT * FROM laboratorio WHERE idLaboratorio=@ID
END
GO

--SELECT DE LABORATORIO DOS
CREATE PROCEDURE SP_SELECT_LABORATORIO_DOS
AS
BEGIN
	SELECT * FROM laboratorio
END
GO

--DELETE DE LABORATORIO
CREATE PROCEDURE SP_DELETE_LABORATORIO
	@ID INT
AS
BEGIN
	DELETE FROM laboratorio WHERE idLaboratorio=@ID
END
GO

--INSERT DE LINEA_ARTICULO
CREATE PROCEDURE SP_INSERT_LINEA_ARTICULO
	@NOMBRE CHAR(50)
AS
BEGIN
	INSERT linea_articulo VALUES(@NOMBRE)
END
GO

--UPDATE DE LINEA_ARTICULO
CREATE PROCEDURE SP_UPDATE_LINEA_ARTICULO
	@ID INT,
	@NOMBRE CHAR(50)
AS
BEGIN
	UPDATE linea_articulo SET nombreLinea=@NOMBRE
	WHERE idLineaArticulo = @ID
END
GO

--SELECT DE LINEA_ARTICULO
CREATE PROCEDURE SP_SELECT_LINEA_ARTICULO
	@ID INT
AS
BEGIN
	SELECT * FROM linea_articulo WHERE idLineaArticulo=@ID
END
GO

--SELECT DE LINEA_ARTICULO
CREATE PROCEDURE SP_SELECT_LINEA_ARTICULO_DOS
AS
BEGIN
	SELECT * FROM linea_articulo
END
GO

--DELETE DE LINEA_ARTICULO
CREATE PROCEDURE SP_DELETE_LINEA_ARTICULO
	@ID INT
AS
BEGIN
	DELETE FROM linea_articulo WHERE idLineaArticulo=@ID
END
GO

--INSERT DE EMPLEADO
CREATE PROCEDURE SP_INSERT_EMPLEADO
	@NOMBRE CHAR(60),
	@APATERNO CHAR(30),
	@AMATERNO CHAR(30),
	@FECHAING DATE,
	@USUARIO CHAR(20),
	@CONTRASENIA CHAR(30),
	@IDROL INT,
	@NUMTELEFONICO INT,
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(40),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31),
	@EMAIL CHAR(50),
	@REDSOCIALUNO CHAR(50),
	@REDSOCIALDOS CHAR(50),
	@IDSUCURSAL INT
AS
BEGIN
	INSERT empleado VALUES(@NOMBRE, @APATERNO, @AMATERNO, @FECHAING, @USUARIO, @CONTRASENIA, @IDROL,
	@NUMTELEFONICO, @CALLE, @NUMEXT, @NUMINT, @COLONIA, @MUNICIPIO, @CP, @ESTADO, @EMAIL, @REDSOCIALUNO,
	@REDSOCIALDOS, @IDSUCURSAL)
END
GO

EXECUTE SP_INSERT_EMPLEADO @NOMBRE='SUPERUSUARIO',@APATERNO='SP',@AMATERNO='SP',@FECHAING='2021-11-25',
@USUARIO='SUPERUSUARIO',@CONTRASENIA='12345',@IDROL='1',@NUMTELEFONICO='',@CALLE='',@NUMEXT='',@NUMINT='',
@COLONIA='',@MUNICIPIO='',@CP='',@ESTADO='',@EMAIL='',@REDSOCIALUNO='',@REDSOCIALDOS='',@IDSUCURSAL='1'
GO

DBCC CHECKIDENT ('empleado', RESEED, 1);

--UPDATE DE EMPLEADO
CREATE PROCEDURE SP_UPDATE_EMPLEADO
	@ID INT,
	@NOMBRE CHAR(60),
	@APATERNO CHAR(30),
	@AMATERNO CHAR(30),
	@FECHAING DATE,
	@USUARIO CHAR(20),
	@CONTRASENIA CHAR(30),
	@IDROL INT,
	@NUMTELEFONICO INT,
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(40),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31),
	@EMAIL CHAR(50),
	@REDSOCIALUNO CHAR(50),
	@REDSOCIALDOS CHAR(50),
	@IDSUCURSAL INT
AS
BEGIN
	UPDATE empleado SET nombreEmpleado=@NOMBRE, aPaternoEmpleado=@APATERNO, aMaternoEmpleado=@AMATERNO, fechaIngresoEmpleado=@FECHAING,
	nombreUsuarioEmpleado=@USUARIO, contraseniaEmpleado=@CONTRASENIA, idRol=@IDROL, numTelefonicoEmpleado=@NUMTELEFONICO, calleEmpleado=@CALLE,
	numExtEmpleado=@NUMEXT, numIntEmpleado=@NUMINT, coloniaEmpleado=@COLONIA, municipioEmpleado=@MUNICIPIO, codigoPostalEmpleado=@CP,
	estadoEmpleado=@ESTADO, emailEmpleado=@EMAIL, redSocialUnoEmpleado=@REDSOCIALUNO, redSocialDosEmpleado=@REDSOCIALDOS, idSucursal=@IDSUCURSAL
	WHERE idEmpleado = @ID
END
GO

--SELECT DE EMPLEADO
CREATE PROCEDURE SP_SELECT_EMPLEADO
	@ID INT
AS
BEGIN
	SELECT * FROM empleado WHERE idEmpleado=@ID
END
GO

--SELECT DE EMPLEADO DOS
CREATE PROCEDURE SP_SELECT_EMPLEADO_DOS
AS
BEGIN
	SELECT * FROM empleado
END
GO

EXECUTE SP_SELECT_EMPLEADO_DOS
GO

--SELECT DE INICIO DE SESION DE EMPLEADO
CREATE PROCEDURE SP_SELECT_INICIO_SESION
	@USUARIO CHAR(20),
	@CONTRASENIA CHAR(30)
AS
BEGIN
	SELECT nombreEmpleado, nombreUsuarioEmpleado, contraseniaEmpleado, idRol FROM empleado WHERE nombreUsuarioEmpleado=@USUARIO AND contraseniaEmpleado=@CONTRASENIA
END
GO

EXECUTE SP_SELECT_INICIO_SESION @USUARIO='SUPERUSUARIO', @CONTRASENIA='12345'
GO

--DELETE DE EMPLEADO
CREATE PROCEDURE SP_DELETE_EMPLEADO
	@ID INT
AS
BEGIN
	DELETE FROM empleado WHERE idEmpleado=@ID
END
GO

EXECUTE SP_DELETE_EMPLEADO @ID='2'
GO

--INSERT DE MEDICO
CREATE PROCEDURE SP_INSERT_MEDICO
	@CEDULA INT,
	@NOMBRECOMPLETO CHAR(120),
	@DIRECCION CHAR(250),
	@ESPECIALIDADMEDICO CHAR(30),
	@TELEFONO INT
AS
BEGIN
	INSERT medico VALUES('', @CEDULA, @NOMBRECOMPLETO, @DIRECCION, @ESPECIALIDADMEDICO, @TELEFONO)
END
GO

--UPDATE DE MEDICO
CREATE PROCEDURE SP_UPDATE_MEDICO
	@ID INT,
	@CEDULA INT,
	@NOMBRECOMPLETO CHAR(120),
	@DIRECCION CHAR(250),
	@ESPECIALIDADMEDICO CHAR(30),
	@TELEFONO INT
AS
BEGIN
	UPDATE medico SET cedulaProfesional=@CEDULA, nombreCompletoMedico=@NOMBRECOMPLETO, direccionConsultorioMedico=@DIRECCION,
	especialidadMedico=@ESPECIALIDADMEDICO, telefonoMedico=@TELEFONO
	WHERE idMedico = @ID
END
GO

--SELECT DE MEDICO
CREATE PROCEDURE SP_SELECT_MEDICO
	@ID INT
AS
BEGIN
	SELECT * FROM medico WHERE idMedico=@ID
END
GO

--INSERT DE ROL
CREATE PROCEDURE SP_INSERT_ROL
	@NOMBRE CHAR(10)
AS
BEGIN
	INSERT rol VALUES(@NOMBRE)
END
GO

EXECUTE SP_INSERT_ROL @NOMBRE='Encargado'
GO
EXECUTE SP_INSERT_ROL @NOMBRE='Supervisor'
GO
EXECUTE SP_INSERT_ROL @NOMBRE='Vendedor'
GO

--UPDATE DE ROL
CREATE PROCEDURE SP_UPDATE_ROL
	@ID INT,
	@NOMBRE CHAR(10)
AS
BEGIN
	UPDATE rol SET nombreRol=@NOMBRE
	WHERE idRol = @ID
END
GO

EXECUTE SP_UPDATE_ROL @ID='1', @NOMBRE='Encargado'
GO

--SELECT DE ROL
CREATE PROCEDURE SP_SELECT_ROL
	@ID INT
AS
BEGIN
	SELECT * FROM rol WHERE idRol=@ID
END
GO

EXECUTE SP_SELECT_ROL @ID='3'
GO

--SELECT DE ROL DOS
CREATE PROCEDURE SP_SELECT_ROL_DOS
AS
BEGIN
	SELECT * FROM rol
END
GO

EXECUTE SP_SELECT_ROL_DOS
GO

DBCC CHECKIDENT ('rol', RESEED, 3);

--DELETE DE ROL
CREATE PROCEDURE SP_DELETE_ROL
	@ID INT
AS
BEGIN
	DELETE FROM rol WHERE idRol=@ID
END
GO

EXECUTE SP_DELETE_ROL @ID='4'
GO

--INSERT DE PROVEEDOR
CREATE PROCEDURE SP_INSERT_PROVEEDOR
	@NOMBRE CHAR(45),
	@FECHAING DATE,
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(40),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31),
	@RFC CHAR(13),
	@TELEFONOFIJO INT,
	@TELEFONOCELULAR INT,
	@FACEBOOK CHAR(50),
	@TWITTER CHAR(50),
	@INSTAGRAM CHAR(50),
	@PAGINAWEB CHAR(150),
	@EMAIL CHAR(50)
AS
BEGIN
	INSERT proveedor VALUES(@NOMBRE, @FECHAING, @CALLE, @NUMEXT, @NUMINT, @COLONIA, @MUNICIPIO,
	@CP, @ESTADO, @RFC, @TELEFONOFIJO, @TELEFONOCELULAR, @FACEBOOK, @TWITTER, @INSTAGRAM, @PAGINAWEB, @EMAIL)
END
GO

--UPDATE DE PROVEEDOR
CREATE PROCEDURE SP_UPDATE_PROVEEDOR
	@ID INT,
	@NOMBRE CHAR(45),
	@FECHAING DATE,
	@CALLE CHAR(30),
	@NUMEXT INT,
	@NUMINT INT,
	@COLONIA CHAR(40),
	@MUNICIPIO CHAR(25),
	@CP INT,
	@ESTADO CHAR(31),
	@RFC CHAR(13),
	@TELEFONOFIJO INT,
	@TELEFONOCELULAR INT,
	@FACEBOOK CHAR(50),
	@TWITTER CHAR(50),
	@INSTAGRAM CHAR(50),
	@PAGINAWEB CHAR(150),
	@EMAIL CHAR(50)
AS
BEGIN
	UPDATE proveedor SET nombreProveedor=@NOMBRE, fechaIngresoProveedor=@FECHAING, calleProveedor=@CALLE, numExtProveedor=@NUMEXT, numIntProveedor=@NUMINT,
	coloniaProveedor=@COLONIA, municipioProveedor=@MUNICIPIO, codigoPostalProveedor=@CP, estadoProveedor=@ESTADO, rfcProveedor=@RFC, telefonoFijo=@TELEFONOFIJO,
	telefonoCelular=@TELEFONOCELULAR, facebookProveedor=@FACEBOOK, twitterProveedor=@TWITTER, instagramProveedor=@INSTAGRAM, paginaWebProveedor=@PAGINAWEB,
	emailProveedor=@EMAIL
	WHERE idProveedor = @ID
END
GO

--SELECT DE PROVEEDOR
CREATE PROCEDURE SP_SELECT_PROVEEDOR
	@ID INT
AS
BEGIN
	SELECT * FROM proveedor WHERE idProveedor=@ID
END
GO

--DELETE DE PROVEEDOR
CREATE PROCEDURE SP_DELETE_PROVEEDOR
	@ID INT
AS
BEGIN
	DELETE FROM proveedor WHERE idProveedor=@ID
END
GO

--INSERT DE COMPRA
CREATE PROCEDURE SP_INSERT_COMPRA
	@IDPROVEEDOR INT,
	@NOMBREPROVEEDOR CHAR(45),
	@SUCURSAL CHAR(50),
	@NUMFACTURA CHAR(10),
	@IVACOMPRA INT,
	@FECHAREG DATE,
	@IDEMPLEADO INT,
	@CREDITOFECHA DATE
AS
BEGIN
	INSERT compra VALUES(@IDPROVEEDOR, @NOMBREPROVEEDOR, @SUCURSAL, @NUMFACTURA, @IVACOMPRA, @FECHAREG, @IDEMPLEADO, @CREDITOFECHA)
END
GO

--UPDATE DE COMPRA
CREATE PROCEDURE SP_UPDATE_COMPRA
	@ID INT,
	@IDPROVEEDOR INT,
	@NOMBREPROVEEDOR CHAR(45),
	@SUCURSAL CHAR(50),
	@NUMFACTURA CHAR(10),
	@IVACOMPRA INT,
	@FECHAREG DATE,
	@IDEMPLEADO INT,
	@CREDITOFECHA DATE
AS
BEGIN
	UPDATE compra SET idProveedor=@IDPROVEEDOR, nombreProveedorCompra=@NOMBREPROVEEDOR, sucursal=@SUCURSAL, numFacturaCompra=@NUMFACTURA, ivaCompra=@IVACOMPRA,
	fechaRegistroCompra=@FECHAREG, idEmpleado=@IDEMPLEADO, creditoFecha=@CREDITOFECHA
	WHERE idCompra = @ID
END
GO

--SELECT DE COMPRA
CREATE PROCEDURE SP_SELECT_COMPRA
	@ID INT
AS
BEGIN
	SELECT * FROM compra WHERE idCompra=@ID
END
GO

--INSERT DE EXISTENCIA
CREATE PROCEDURE SP_INSERT_EXISTENCIA
	@UNIDADES INT,
	@FECHACADUCIDAD DATE
AS
BEGIN
	INSERT existencia VALUES(@UNIDADES, @FECHACADUCIDAD)
END
GO

--UPDATE DE EXISTENCIA
CREATE PROCEDURE SP_UPDATE_EXISTENCIA
	@ID INT,
	@UNIDADES INT,
	@FECHACADUCIDAD DATE
AS
BEGIN
	UPDATE existencia SET unidadesExistencia=@UNIDADES, fechaCaducidadExistencia=@FECHACADUCIDAD
	WHERE idExistencia = @ID
END
GO

--SELECT DE EXISTENCIA
CREATE PROCEDURE SP_SELECT_EXISTENCIA
	@ID INT
AS
BEGIN
	SELECT * FROM existencia WHERE idExistencia=@ID
END
GO

--INSERT DE LOTE_ARTICULO
CREATE PROCEDURE SP_INSERT_LOTE_ARTICULO
	@CLAVELOTE CHAR(20),
	@IDEXISTENCIA INT
AS
BEGIN
	INSERT lote_articulo VALUES(@CLAVELOTE, @IDEXISTENCIA)
END
GO

--UPDATE DE LOTE_ARTICULO
CREATE PROCEDURE SP_UPDATE_LOTE_ARTICULO
	@ID INT,
	@CLAVELOTE CHAR(20),
	@IDEXISTENCIA INT
AS
BEGIN
	UPDATE lote_articulo SET claveLoteArticulo=@CLAVELOTE, idExistencia=@IDEXISTENCIA
	WHERE idLoteArticulo = @ID
END
GO

--SELECT DE LOTE_ARTICULO
CREATE PROCEDURE SP_SELECT_LOTE_ARTICULO
	@ID INT
AS
BEGIN
	SELECT * FROM lote_articulo WHERE idLoteArticulo=@ID
END
GO

--INSERT DE ARTICULO
CREATE PROCEDURE SP_INSERT_ARTICULO
	@CODIGOBARRAS INT,
	@DESCRIPCION CHAR(150),
	@IDLINEA INT,
	@IDLABORATORIO INT,
	@IDLOTE INT,
	@FECHAINGRESO DATE,
	@COSTO FLOAT,
	@FORMULA CHAR(70),
	@PRECIOLISTADO FLOAT,
	@PRECIOPUBLICO FLOAT,
	@RESTRINGIDO CHAR(2),
	@BLOQUEADO CHAR(2),
	@MININVENTARIO INT,
	@MAXINVENTARIO INT,
	@REORDENUNIDADES INT,
	@EXENTOIVA CHAR(2),
	@GRANEL CHAR(2)
AS
BEGIN
	INSERT articulo VALUES(@CODIGOBARRAS, @DESCRIPCION, @IDLINEA, @IDLABORATORIO, @IDLOTE, @FECHAINGRESO, @COSTO, @FORMULA, @PRECIOLISTADO, @PRECIOPUBLICO, @RESTRINGIDO, @BLOQUEADO,
	@MININVENTARIO, @MAXINVENTARIO, @REORDENUNIDADES, @EXENTOIVA, @GRANEL)
END
GO

--UPDATE DE ARTICULO
CREATE PROCEDURE SP_UPDATE_ARTICULO
	@CODIGOBARRAS INT,
	@DESCRIPCION CHAR(150),
	@IDLINEA INT,
	@IDLABORATORIO INT,
	@IDLOTE INT,
	@FECHAINGRESO DATE,
	@COSTO FLOAT,
	@FORMULA CHAR(70),
	@PRECIOLISTADO FLOAT,
	@PRECIOPUBLICO FLOAT,
	@RESTRINGIDO CHAR(2),
	@BLOQUEADO CHAR(2),
	@MININVENTARIO INT,
	@MAXINVENTARIO INT,
	@REORDENUNIDADES INT,
	@EXENTOIVA CHAR(2),
	@GRANEL CHAR(2)
AS
BEGIN
	UPDATE articulo SET descripcionArticulo=@DESCRIPCION, idLineaArticulo=@IDLINEA, idLaboratorio=@IDLABORATORIO, idLote=@IDLOTE, fechaIngresoArticulo=@FECHAINGRESO,
	costoArticulo=@COSTO, formulaArticulo=@FORMULA, precioListadoArticulo=@PRECIOLISTADO, precioPublicoArticulo=@PRECIOPUBLICO, restringidoArticulo=@RESTRINGIDO,
	bloqueadoArticulo=@BLOQUEADO, minInventarioArticulo=@MININVENTARIO, maxInventarioArticulo=@MAXINVENTARIO, reordenUnidadesArticulo=@REORDENUNIDADES, exentoIvaArticulo=@EXENTOIVA,
	granelArticulo=@GRANEL
	WHERE codigoBarrasArticulo = @CODIGOBARRAS
END
GO

--SELECT DE ARTICULO
CREATE PROCEDURE SP_SELECT_ARTICULO
	@CODIGOBARRAS INT
AS
BEGIN
	SELECT * FROM articulo WHERE codigoBarrasArticulo=@CODIGOBARRAS
END
GO

--INSERT DE ADQUISICION
CREATE PROCEDURE SP_INSERT_ADQUISICION
	@IDCOMPRA INT,
	@CODIGOBARRAS INT,
	@FECHAADQUISICION DATE
AS
BEGIN
	INSERT adquisicion VALUES(@IDCOMPRA, @CODIGOBARRAS, @FECHAADQUISICION)
END
GO

--SELECT DE ADQUISICION
CREATE PROCEDURE SP_SELECT_ADQUISICION
	@IDCOMPRA INT,
	@CODIGOBARRAS INT
AS
BEGIN
	SELECT * FROM adquisicion WHERE codigoBarrasArticulo=@CODIGOBARRAS AND idCompra=@IDCOMPRA
END
GO

--INSERT DE VENTA
CREATE PROCEDURE SP_INSERT_VENTA
	@FECHA DATE,
	@HORAVENTA TIME,
	@TOTALVENTA FLOAT,
	@TIPOVENTA CHAR(8),
	@IDEMPLEADO INT,
	@IDRECETAMEDICA INT
AS
BEGIN
	INSERT venta VALUES(@FECHA, @HORAVENTA, @TOTALVENTA, @TIPOVENTA, @IDEMPLEADO, @IDRECETAMEDICA)
END
GO

--SELECT DE VENTA
CREATE PROCEDURE SP_SELECT_VENTA
	@ID INT
AS
BEGIN
	SELECT * FROM venta WHERE idVenta=@ID
END
GO

--DELETE DE DETALLE_VENTA
CREATE PROCEDURE SP_DELETE_VENTA
	@ID INT
AS
BEGIN
	DELETE FROM venta WHERE idVenta=@ID
END
GO

--INSERT DE DETALLE_VENTA
CREATE PROCEDURE SP_INSERT_DETALLE_VENTA
	@CODIGOBARRAS INT,
	@IDVENTA INT,
	@CANTIDADARTICULO INT,
	@SUBTOTALVENTA FLOAT,
	@CLAVELOTEARTICULO CHAR(20),
	@FECHACADUCIDAD DATE
AS
BEGIN
	INSERT detalle_venta VALUES(@CODIGOBARRAS, @IDVENTA, @CANTIDADARTICULO, @SUBTOTALVENTA, @CLAVELOTEARTICULO, @FECHACADUCIDAD)
END
GO

--SELECT DE DETALLE_VENTA
CREATE PROCEDURE SP_SELECT_DETALLE_VENTA
	@CODIGOBARRAS INT,
	@IDVENTA INT
AS
BEGIN
	SELECT * FROM detalle_venta WHERE codigoBarrasArticulo=@CODIGOBARRAS AND idVenta=@IDVENTA
END
GO

--DELETE DE DETALLE_VENTA
CREATE PROCEDURE SP_DELETE_DETALLE_VENTA
	@CODIGOBARRAS INT,
	@IDVENTA INT
AS
BEGIN
	DELETE FROM detalle_venta WHERE codigoBarrasArticulo=@CODIGOBARRAS AND idVenta=@IDVENTA
END
GO